DATA FLOW;
  INPUT DEPTH RATE;
  LOGDEPTH = LOG(DEPTH);
  LOGRATE = LOG(RATE);
  DEPTHSQ = DEPTH*DEPTH;
DATALINES;
  0.34 0.636
  0.29 0.319
  0.28 0.734
  0.42 1.327
  0.29 0.487
  0.41 0.924
  0.76 7.350
  0.73 5.890
  0.46 1.979
  0.40 1.124
;

PROC PLOT DATA=FLOW;
  PLOT RATE*DEPTH;
RUN;

PROC CORR DATA=FLOW;
  VAR RATE DEPTH;
RUN;

PROC REG DATA=FLOW;
  TITLE 'Regression for Rate versus Depth';
  MODEL RATE=DEPTH;
  PLOT RESIDUAL.*DEPTH;
RUN;

PROC PLOT DATA=FLOW;
  PLOT LOGRATE*LOGDEPTH;
RUN;

PROC CORR DATA=FLOW;
  VAR LOGRATE LOGDEPTH;
RUN;

PROC REG DATA=FLOW;
  TITLE 'Regression for log(Rate) versus log(Depth)';
  MODEL LOGRATE=LOGDEPTH;
  PLOT RESIDUAL.*LOGDEPTH;
RUN;

PROC REG DATA=FLOW;
  TITLE 'Regression for Rate versus Depth and Depth^2';
  MODEL RATE=DEPTH DEPTHSQ;
  PLOT RESIDUAL.*DEPTH;
RUN;
